'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программным средством.
'     Версия среды выполнения: 4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создан повторно.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Isocline.Properties


    ''' <summary>
    '''   Класс ресурсов со строгим типом для поиска локализованных строк и пр.
    ''' </summary>
    ' Этот класс был автоматически создан при помощи StronglyTypedResourceBuilder
    ' класс с помощью таких средств, как ResGen или Visual Studio.
    ' Для добавления или удаления члена измените файл .ResX, а затем перезапустите ResGen
    ' с параметром /str или заново постройте свой VS-проект.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Возврат кэшированного экземпляра ResourceManager, используемого этим классом.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If resourceMan Is Nothing Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Isocline.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Переопределяет свойство CurrentUICulture текущего потока для всех
        '''   подстановки ресурсов с помощью этого класса ресурсов со строгим типом.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
